//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct ActivityLogEntryQueryResultModel: APIModel {

    /** Gets or sets the items. */
    public var items: [ActivityLogEntryModel]?

    /** The index of the first record in Items. */
    public var startIndex: Int?

    /** The total number of records available. */
    public var totalRecordCount: Int?

    public init(items: [ActivityLogEntryModel]? = nil, startIndex: Int? = nil, totalRecordCount: Int? = nil) {
        self.items = items
        self.startIndex = startIndex
        self.totalRecordCount = totalRecordCount
    }

    public init(from decoder: Decoder) throws {
        let decoderContainer = try decoder.container(keyedBy: StringCodingKey.self)

        items = try decoderContainer.decodeArrayIfPresent("Items")
        startIndex = try decoderContainer.decodeIfPresent("StartIndex")
        totalRecordCount = try decoderContainer.decodeIfPresent("TotalRecordCount")
    }

    public func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: StringCodingKey.self)

        try encoderContainer.encodeIfPresent(items, forKey: "Items")
        try encoderContainer.encodeIfPresent(startIndex, forKey: "StartIndex")
        try encoderContainer.encodeIfPresent(totalRecordCount, forKey: "TotalRecordCount")
    }

}
