//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** The admin notification dto. */
public struct AdminNotificationDtoModel: APIModel {

    /** Gets or sets the notification description. */
    public var description: String?

    /** Gets or sets the notification name. */
    public var name: String?

    public var notificationLevel: NotificationLevel?

    /** Gets or sets the notification url. */
    public var url: String?

    public init(description: String? = nil, name: String? = nil, notificationLevel: NotificationLevel? = nil, url: String? = nil) {
        self.description = description
        self.name = name
        self.notificationLevel = notificationLevel
        self.url = url
    }

    public init(from decoder: Decoder) throws {
        let decoderContainer = try decoder.container(keyedBy: StringCodingKey.self)

        description = try decoderContainer.decodeIfPresent("Description")
        name = try decoderContainer.decodeIfPresent("Name")
        notificationLevel = try decoderContainer.decodeIfPresent("NotificationLevel")
        url = try decoderContainer.decodeIfPresent("Url")
    }

    public func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: StringCodingKey.self)

        try encoderContainer.encodeIfPresent(description, forKey: "Description")
        try encoderContainer.encodeIfPresent(name, forKey: "Name")
        try encoderContainer.encodeIfPresent(notificationLevel, forKey: "NotificationLevel")
        try encoderContainer.encodeIfPresent(url, forKey: "Url")
    }

}
