//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public enum CollectionTypeOptions: String, Codable, Equatable, CaseIterable {
    case movies = "Movies"
    case tvShows = "TvShows"
    case music = "Music"
    case musicVideos = "MusicVideos"
    case homeVideos = "HomeVideos"
    case boxSets = "BoxSets"
    case books = "Books"
    case mixed = "Mixed"
}
