//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct DeviceProfileInfoModel: APIModel {

    /** Gets or sets the identifier. */
    public var id: String?

    /** Gets or sets the name. */
    public var name: String?

    public var type: DeviceProfileType?

    public init(id: String? = nil, name: String? = nil, type: DeviceProfileType? = nil) {
        self.id = id
        self.name = name
        self.type = type
    }

    public init(from decoder: Decoder) throws {
        let decoderContainer = try decoder.container(keyedBy: StringCodingKey.self)

        id = try decoderContainer.decodeIfPresent("Id")
        name = try decoderContainer.decodeIfPresent("Name")
        type = try decoderContainer.decodeIfPresent("Type")
    }

    public func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: StringCodingKey.self)

        try encoderContainer.encodeIfPresent(id, forKey: "Id")
        try encoderContainer.encodeIfPresent(name, forKey: "Name")
        try encoderContainer.encodeIfPresent(type, forKey: "Type")
    }

}
