//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public enum DlnaProfileType: String, Codable, Equatable, CaseIterable {
    case audio = "Audio"
    case video = "Video"
    case photo = "Photo"
}
