//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** An enum that represents a day of the week, weekdays, weekends, or all days. */
/** An enum that represents a day of the week, weekdays, weekends, or all days. */
public enum DynamicDayOfWeek: String, Codable, Equatable, CaseIterable {
    case sunday = "Sunday"
    case monday = "Monday"
    case tuesday = "Tuesday"
    case wednesday = "Wednesday"
    case thursday = "Thursday"
    case friday = "Friday"
    case saturday = "Saturday"
    case everyday = "Everyday"
    case weekday = "Weekday"
    case weekend = "Weekend"
}
