//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public enum EncodingContext: String, Codable, Equatable, CaseIterable {
    case streaming = "Streaming"
    case `static` = "Static"
}
