//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Class FontFile. */
public struct FontFileModel: APIModel {

    /** Gets or sets the date created. */
    public var dateCreated: DateTime?

    /** Gets or sets the date modified. */
    public var dateModified: DateTime?

    /** Gets or sets the name. */
    public var name: String?

    /** Gets or sets the size. */
    public var size: Int?

    public init(dateCreated: DateTime? = nil, dateModified: DateTime? = nil, name: String? = nil, size: Int? = nil) {
        self.dateCreated = dateCreated
        self.dateModified = dateModified
        self.name = name
        self.size = size
    }

    public init(from decoder: Decoder) throws {
        let decoderContainer = try decoder.container(keyedBy: StringCodingKey.self)

        dateCreated = try decoderContainer.decodeIfPresent("DateCreated")
        dateModified = try decoderContainer.decodeIfPresent("DateModified")
        name = try decoderContainer.decodeIfPresent("Name")
        size = try decoderContainer.decodeIfPresent("Size")
    }

    public func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: StringCodingKey.self)

        try encoderContainer.encodeIfPresent(dateCreated, forKey: "DateCreated")
        try encoderContainer.encodeIfPresent(dateModified, forKey: "DateModified")
        try encoderContainer.encodeIfPresent(name, forKey: "Name")
        try encoderContainer.encodeIfPresent(size, forKey: "Size")
    }

}
