//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct ForgotPasswordResultModel: APIModel {

    public var action: ForgotPasswordAction?

    /** Gets or sets the pin expiration date. */
    public var pinExpirationDate: DateTime?

    /** Gets or sets the pin file. */
    public var pinFile: String?

    public init(action: ForgotPasswordAction? = nil, pinExpirationDate: DateTime? = nil, pinFile: String? = nil) {
        self.action = action
        self.pinExpirationDate = pinExpirationDate
        self.pinFile = pinFile
    }

    public init(from decoder: Decoder) throws {
        let decoderContainer = try decoder.container(keyedBy: StringCodingKey.self)

        action = try decoderContainer.decodeIfPresent("Action")
        pinExpirationDate = try decoderContainer.decodeIfPresent("PinExpirationDate")
        pinFile = try decoderContainer.decodeIfPresent("PinFile")
    }

    public func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: StringCodingKey.self)

        try encoderContainer.encodeIfPresent(action, forKey: "Action")
        try encoderContainer.encodeIfPresent(pinExpirationDate, forKey: "PinExpirationDate")
        try encoderContainer.encodeIfPresent(pinFile, forKey: "PinFile")
    }

}
