//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Forgot Password Pin enter request body DTO. */
public struct ForgotPasswordPinDtoModel: APIModel {

    /** Gets or sets the entered pin to have the password reset. */
    public var pin: String

    public init(pin: String) {
        self.pin = pin
    }

    public init(from decoder: Decoder) throws {
        let decoderContainer = try decoder.container(keyedBy: StringCodingKey.self)

        pin = try decoderContainer.decode("Pin")
    }

    public func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: StringCodingKey.self)

        try encoderContainer.encode(pin, forKey: "Pin")
    }

}
