//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct GeneralCommandModel: APIModel {

    public var arguments: [String: String]?

    public var controllingUserId: ID?

    public var name: GeneralCommandType?

    public init(arguments: [String: String]? = nil, controllingUserId: ID? = nil, name: GeneralCommandType? = nil) {
        self.arguments = arguments
        self.controllingUserId = controllingUserId
        self.name = name
    }

    public init(from decoder: Decoder) throws {
        let decoderContainer = try decoder.container(keyedBy: StringCodingKey.self)

        arguments = try decoderContainer.decodeIfPresent("Arguments")
        controllingUserId = try decoderContainer.decodeIfPresent("ControllingUserId")
        name = try decoderContainer.decodeIfPresent("Name")
    }

    public func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: StringCodingKey.self)

        try encoderContainer.encodeIfPresent(arguments, forKey: "Arguments")
        try encoderContainer.encodeIfPresent(controllingUserId, forKey: "ControllingUserId")
        try encoderContainer.encodeIfPresent(name, forKey: "Name")
    }

}
