//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Enum GroupShuffleMode. */
/** Enum GroupShuffleMode. */
public enum GroupShuffleMode: String, Codable, Equatable, CaseIterable {
    case sorted = "Sorted"
    case shuffle = "Shuffle"
}
