//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct HttpHeaderInfoModel: APIModel {

    public var match: HeaderMatchType?

    public var name: String?

    public var value: String?

    public init(match: HeaderMatchType? = nil, name: String? = nil, value: String? = nil) {
        self.match = match
        self.name = name
        self.value = value
    }

    public init(from decoder: Decoder) throws {
        let decoderContainer = try decoder.container(keyedBy: StringCodingKey.self)

        match = try decoderContainer.decodeIfPresent("Match")
        name = try decoderContainer.decodeIfPresent("Name")
        value = try decoderContainer.decodeIfPresent("Value")
    }

    public func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: StringCodingKey.self)

        try encoderContainer.encodeIfPresent(match, forKey: "Match")
        try encoderContainer.encodeIfPresent(name, forKey: "Name")
        try encoderContainer.encodeIfPresent(value, forKey: "Value")
    }

}
