//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Enum IsoType. */
/** Enum IsoType. */
public enum IsoType: String, Codable, Equatable, CaseIterable {
    case dvd = "Dvd"
    case bluRay = "BluRay"
}
