//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct LiveStreamResponseModel: APIModel {

    public var mediaSource: MediaSourceInfoModel?

    public init(mediaSource: MediaSourceInfoModel? = nil) {
        self.mediaSource = mediaSource
    }

    public init(from decoder: Decoder) throws {
        let decoderContainer = try decoder.container(keyedBy: StringCodingKey.self)

        mediaSource = try decoderContainer.decodeIfPresent("MediaSource")
    }

    public func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: StringCodingKey.self)

        try encoderContainer.encodeIfPresent(mediaSource, forKey: "MediaSource")
    }

}
