//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public enum MediaSourceType: String, Codable, Equatable, CaseIterable {
    case `default` = "Default"
    case grouping = "Grouping"
    case placeholder = "Placeholder"
}
