//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Enum MediaStreamType. */
/** Enum MediaStreamType. */
public enum MediaStreamType: String, Codable, Equatable, CaseIterable {
    case audio = "Audio"
    case video = "Video"
    case subtitle = "Subtitle"
    case embeddedImage = "EmbeddedImage"
}
