//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct MessageCommandModel: APIModel {

    public var text: String

    public var header: String?

    public var timeoutMs: Int?

    public init(text: String, header: String? = nil, timeoutMs: Int? = nil) {
        self.text = text
        self.header = header
        self.timeoutMs = timeoutMs
    }

    public init(from decoder: Decoder) throws {
        let decoderContainer = try decoder.container(keyedBy: StringCodingKey.self)

        text = try decoderContainer.decode("Text")
        header = try decoderContainer.decodeIfPresent("Header")
        timeoutMs = try decoderContainer.decodeIfPresent("TimeoutMs")
    }

    public func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: StringCodingKey.self)

        try encoderContainer.encode(text, forKey: "Text")
        try encoderContainer.encodeIfPresent(header, forKey: "Header")
        try encoderContainer.encodeIfPresent(timeoutMs, forKey: "TimeoutMs")
    }

}
