//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Enum MetadataFields. */
/** Enum MetadataFields. */
public enum MetadataField: String, Codable, Equatable, CaseIterable {
    case cast = "Cast"
    case genres = "Genres"
    case productionLocations = "ProductionLocations"
    case studios = "Studios"
    case tags = "Tags"
    case name = "Name"
    case overview = "Overview"
    case runtime = "Runtime"
    case officialRating = "OfficialRating"
}
