//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Class NewGroupRequestDto. */
public struct NewGroupRequestDtoModel: APIModel {

    /** Gets or sets the group name. */
    public var groupName: String?

    public init(groupName: String? = nil) {
        self.groupName = groupName
    }

    public init(from decoder: Decoder) throws {
        let decoderContainer = try decoder.container(keyedBy: StringCodingKey.self)

        groupName = try decoderContainer.decodeIfPresent("GroupName")
    }

    public func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: StringCodingKey.self)

        try encoderContainer.encodeIfPresent(groupName, forKey: "GroupName")
    }

}
