//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** The quick connect request body. */
public struct QuickConnectDtoModel: APIModel {

    /** Gets or sets the quick connect token. */
    public var token: String

    public init(token: String) {
        self.token = token
    }

    public init(from decoder: Decoder) throws {
        let decoderContainer = try decoder.container(keyedBy: StringCodingKey.self)

        token = try decoderContainer.decode("Token")
    }

    public func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: StringCodingKey.self)

        try encoderContainer.encode(token, forKey: "Token")
    }

}
