//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Class RemoteImageResult. */
public struct RemoteImageResultModel: APIModel {

    /** Gets or sets the images. */
    public var images: [RemoteImageInfoModel]?

    /** Gets or sets the providers. */
    public var providers: [String]?

    /** Gets or sets the total record count. */
    public var totalRecordCount: Int?

    public init(images: [RemoteImageInfoModel]? = nil, providers: [String]? = nil, totalRecordCount: Int? = nil) {
        self.images = images
        self.providers = providers
        self.totalRecordCount = totalRecordCount
    }

    public init(from decoder: Decoder) throws {
        let decoderContainer = try decoder.container(keyedBy: StringCodingKey.self)

        images = try decoderContainer.decodeArrayIfPresent("Images")
        providers = try decoderContainer.decodeArrayIfPresent("Providers")
        totalRecordCount = try decoderContainer.decodeIfPresent("TotalRecordCount")
    }

    public func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: StringCodingKey.self)

        try encoderContainer.encodeIfPresent(images, forKey: "Images")
        try encoderContainer.encodeIfPresent(providers, forKey: "Providers")
        try encoderContainer.encodeIfPresent(totalRecordCount, forKey: "TotalRecordCount")
    }

}
