//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Enum SendCommandType. */
/** Enum SendCommandType. */
public enum SendCommandType: String, Codable, Equatable, CaseIterable {
    case unpause = "Unpause"
    case pause = "Pause"
    case stop = "Stop"
    case seek = "Seek"
}
