//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Enum SeriesStatus. */
/** Enum SeriesStatus. */
public enum SeriesStatus: String, Codable, Equatable, CaseIterable {
    case continuing = "Continuing"
    case ended = "Ended"
}
