//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Class SetPlaylistItemRequestDto. */
public struct SetPlaylistItemRequestDtoModel: APIModel {

    /** Gets or sets the playlist identifier of the playing item. */
    public var playlistItemId: ID?

    public init(playlistItemId: ID? = nil) {
        self.playlistItemId = playlistItemId
    }

    public init(from decoder: Decoder) throws {
        let decoderContainer = try decoder.container(keyedBy: StringCodingKey.self)

        playlistItemId = try decoderContainer.decodeIfPresent("PlaylistItemId")
    }

    public func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: StringCodingKey.self)

        try encoderContainer.encodeIfPresent(playlistItemId, forKey: "PlaylistItemId")
    }

}
