//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** An enum representing the sorting order. */
/** An enum representing the sorting order. */
public enum SortOrder: String, Codable, Equatable, CaseIterable {
    case ascending = "Ascending"
    case descending = "Descending"
}
