//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** The startup configuration DTO. */
public struct StartupConfigurationDtoModel: APIModel {

    /** Gets or sets the metadata country code. */
    public var metadataCountryCode: String?

    /** Gets or sets the preferred language for the metadata. */
    public var preferredMetadataLanguage: String?

    /** Gets or sets UI language culture. */
    public var uICulture: String?

    public init(metadataCountryCode: String? = nil, preferredMetadataLanguage: String? = nil, uICulture: String? = nil) {
        self.metadataCountryCode = metadataCountryCode
        self.preferredMetadataLanguage = preferredMetadataLanguage
        self.uICulture = uICulture
    }

    public init(from decoder: Decoder) throws {
        let decoderContainer = try decoder.container(keyedBy: StringCodingKey.self)

        metadataCountryCode = try decoderContainer.decodeIfPresent("MetadataCountryCode")
        preferredMetadataLanguage = try decoderContainer.decodeIfPresent("PreferredMetadataLanguage")
        uICulture = try decoderContainer.decodeIfPresent("UICulture")
    }

    public func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: StringCodingKey.self)

        try encoderContainer.encodeIfPresent(metadataCountryCode, forKey: "MetadataCountryCode")
        try encoderContainer.encodeIfPresent(preferredMetadataLanguage, forKey: "PreferredMetadataLanguage")
        try encoderContainer.encodeIfPresent(uICulture, forKey: "UICulture")
    }

}
