//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** An enum representing a subtitle playback mode. */
/** An enum representing a subtitle playback mode. */
public enum SubtitlePlaybackMode: String, Codable, Equatable, CaseIterable {
    case `default` = "Default"
    case always = "Always"
    case onlyForced = "OnlyForced"
    case none = "None"
    case smart = "Smart"
}
