//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public enum SubtitleDeliveryMethod: String, Codable, Equatable, CaseIterable {
    case encode = "Encode"
    case embed = "Embed"
    case external = "External"
    case hls = "Hls"
}
