//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public enum Video3DFormat: String, Codable, Equatable, CaseIterable {
    case halfSideBySide = "HalfSideBySide"
    case fullSideBySide = "FullSideBySide"
    case fullTopAndBottom = "FullTopAndBottom"
    case halfTopAndBottom = "HalfTopAndBottom"
    case mvc = "MVC"
}
