//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension JellyfinAPI.User {

    /** Authenticates a user with quick connect. */
    public enum AuthenticateWithQuickConnect {

        public static let service = APIService<Response>(id: "AuthenticateWithQuickConnect", tag: "User", method: "POST", path: "/Users/AuthenticateWithQuickConnect", hasBody: true, securityRequirements: [])

        public final class Request: APIRequest<Response> {

            public var body: QuickConnectDtoModel

            public init(body: QuickConnectDtoModel, encoder: RequestEncoder? = nil) {
                self.body = body
                super.init(service: AuthenticateWithQuickConnect.service) { defaultEncoder in
                    return try (encoder ?? defaultEncoder).encode(body)
                }
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = AuthenticationResultModel

            /** User authenticated. */
            case status200(AuthenticationResultModel)

            /** Missing token. */
            case status400

            public var success: AuthenticationResultModel? {
                switch self {
                case .status200(let response): return response
                default: return nil
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                default: return ()
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                case .status400: return 400
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                case .status400: return false
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(AuthenticationResultModel.self, from: data))
                case 400: self = .status400
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
