//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension JellyfinAPI.User {

    /** Initiates the forgot password process for a local user. */
    public enum ForgotPassword {

        public static let service = APIService<Response>(id: "ForgotPassword", tag: "User", method: "POST", path: "/Users/ForgotPassword", hasBody: true, securityRequirements: [])

        public final class Request: APIRequest<Response> {

            public var body: ForgotPasswordDtoModel

            public init(body: ForgotPasswordDtoModel, encoder: RequestEncoder? = nil) {
                self.body = body
                super.init(service: ForgotPassword.service) { defaultEncoder in
                    return try (encoder ?? defaultEncoder).encode(body)
                }
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = ForgotPasswordResultModel

            /** Password reset process started. */
            case status200(ForgotPasswordResultModel)

            public var success: ForgotPasswordResultModel? {
                switch self {
                case .status200(let response): return response
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(ForgotPasswordResultModel.self, from: data))
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
