//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension JellyfinAPI.DisplayPreferences {

    /** Update Display Preferences. */
    public enum UpdateDisplayPreferences {

        public static let service = APIService<Response>(id: "UpdateDisplayPreferences", tag: "DisplayPreferences", method: "POST", path: "/DisplayPreferences/{displayPreferencesId}", hasBody: true, securityRequirements: [SecurityRequirement(type: "CustomAuthentication", scopes: ["DefaultAuthorization"])])

        public final class Request: APIRequest<Response> {

            public struct Options {

                /** Display preferences id. */
                public var displayPreferencesId: String

                /** User Id. */
                public var userId: ID

                /** Client. */
                public var client: String

                public init(displayPreferencesId: String, userId: ID, client: String) {
                    self.displayPreferencesId = displayPreferencesId
                    self.userId = userId
                    self.client = client
                }
            }

            public var options: Options

            public var body: DisplayPreferencesDtoModel

            public init(body: DisplayPreferencesDtoModel, options: Options, encoder: RequestEncoder? = nil) {
                self.body = body
                self.options = options
                super.init(service: UpdateDisplayPreferences.service) { defaultEncoder in
                    return try (encoder ?? defaultEncoder).encode(body)
                }
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(displayPreferencesId: String, userId: ID, client: String, body: DisplayPreferencesDtoModel) {
                let options = Options(displayPreferencesId: displayPreferencesId, userId: userId, client: client)
                self.init(body: body, options: options)
            }

            public override var path: String {
                return super.path.replacingOccurrences(of: "{" + "displayPreferencesId" + "}", with: "\(self.options.displayPreferencesId)")
            }

            public override var queryParameters: [String: Any] {
                var params: [String: Any] = [:]
                params["userId"] = options.userId.encode()
                params["client"] = options.client
                return params
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = Void

            /** Display preferences updated. */
            case status204

            /** Unauthorized */
            case status401

            /** Forbidden */
            case status403

            public var success: Void? {
                switch self {
                case .status204: return ()
                default: return nil
                }
            }

            public var response: Any {
                switch self {
                default: return ()
                }
            }

            public var statusCode: Int {
                switch self {
                case .status204: return 204
                case .status401: return 401
                case .status403: return 403
                }
            }

            public var successful: Bool {
                switch self {
                case .status204: return true
                case .status401: return false
                case .status403: return false
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 204: self = .status204
                case 401: self = .status401
                case 403: self = .status403
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
