//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension JellyfinAPI.Items {

    /** Gets items based on a query. */
    public enum GetResumeItems {

        public static let service = APIService<Response>(id: "GetResumeItems", tag: "Items", method: "GET", path: "/Users/{userId}/Items/Resume", hasBody: false, securityRequirements: [SecurityRequirement(type: "CustomAuthentication", scopes: ["DefaultAuthorization"])])

        public final class Request: APIRequest<Response> {

            public struct Options {

                /** The user id. */
                public var userId: ID

                /** The start index. */
                public var startIndex: Int?

                /** The item limit. */
                public var limit: Int?

                /** The search term. */
                public var searchTerm: String?

                /** Specify this to localize the search to a specific item or folder. Omit to use the root. */
                public var parentId: ID?

                /** Optional. Specify additional fields of information to return in the output. This allows multiple, comma delimited. Options: Budget, Chapters, DateCreated, Genres, HomePageUrl, IndexOptions, MediaStreams, Overview, ParentId, Path, People, ProviderIds, PrimaryImageAspectRatio, Revenue, SortName, Studios, Taglines. */
                public var fields: [ItemFields]?

                /** Optional. Filter by MediaType. Allows multiple, comma delimited. */
                public var mediaTypes: [String]?

                /** Optional. Include user data. */
                public var enableUserData: Bool?

                /** Optional. The max number of images to return, per image type. */
                public var imageTypeLimit: Int?

                /** Optional. The image types to include in the output. */
                public var enableImageTypes: [ImageType]?

                /** Optional. If specified, results will be filtered based on item type. This allows multiple, comma delimited. */
                public var excludeItemTypes: [String]?

                /** Optional. If specified, results will be filtered based on the item type. This allows multiple, comma delimited. */
                public var includeItemTypes: [String]?

                /** Optional. Enable the total record count. */
                public var enableTotalRecordCount: Bool?

                /** Optional. Include image information in output. */
                public var enableImages: Bool?

                public init(userId: ID, startIndex: Int? = nil, limit: Int? = nil, searchTerm: String? = nil, parentId: ID? = nil, fields: [ItemFields]? = nil, mediaTypes: [String]? = nil, enableUserData: Bool? = nil, imageTypeLimit: Int? = nil, enableImageTypes: [ImageType]? = nil, excludeItemTypes: [String]? = nil, includeItemTypes: [String]? = nil, enableTotalRecordCount: Bool? = nil, enableImages: Bool? = nil) {
                    self.userId = userId
                    self.startIndex = startIndex
                    self.limit = limit
                    self.searchTerm = searchTerm
                    self.parentId = parentId
                    self.fields = fields
                    self.mediaTypes = mediaTypes
                    self.enableUserData = enableUserData
                    self.imageTypeLimit = imageTypeLimit
                    self.enableImageTypes = enableImageTypes
                    self.excludeItemTypes = excludeItemTypes
                    self.includeItemTypes = includeItemTypes
                    self.enableTotalRecordCount = enableTotalRecordCount
                    self.enableImages = enableImages
                }
            }

            public var options: Options

            public init(options: Options) {
                self.options = options
                super.init(service: GetResumeItems.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(userId: ID, startIndex: Int? = nil, limit: Int? = nil, searchTerm: String? = nil, parentId: ID? = nil, fields: [ItemFields]? = nil, mediaTypes: [String]? = nil, enableUserData: Bool? = nil, imageTypeLimit: Int? = nil, enableImageTypes: [ImageType]? = nil, excludeItemTypes: [String]? = nil, includeItemTypes: [String]? = nil, enableTotalRecordCount: Bool? = nil, enableImages: Bool? = nil) {
                let options = Options(userId: userId, startIndex: startIndex, limit: limit, searchTerm: searchTerm, parentId: parentId, fields: fields, mediaTypes: mediaTypes, enableUserData: enableUserData, imageTypeLimit: imageTypeLimit, enableImageTypes: enableImageTypes, excludeItemTypes: excludeItemTypes, includeItemTypes: includeItemTypes, enableTotalRecordCount: enableTotalRecordCount, enableImages: enableImages)
                self.init(options: options)
            }

            public override var path: String {
                return super.path.replacingOccurrences(of: "{" + "userId" + "}", with: "\(self.options.userId.encode())")
            }

            public override var queryParameters: [String: Any] {
                var params: [String: Any] = [:]
                if let startIndex = options.startIndex {
                  params["startIndex"] = startIndex
                }
                if let limit = options.limit {
                  params["limit"] = limit
                }
                if let searchTerm = options.searchTerm {
                  params["searchTerm"] = searchTerm
                }
                if let parentId = options.parentId?.encode() {
                  params["parentId"] = parentId
                }
                if let fields = options.fields?.encode().map({ String(describing: $0) }).joined(separator: ",") {
                  params["fields"] = fields
                }
                if let mediaTypes = options.mediaTypes?.joined(separator: ",") {
                  params["mediaTypes"] = mediaTypes
                }
                if let enableUserData = options.enableUserData {
                  params["enableUserData"] = enableUserData
                }
                if let imageTypeLimit = options.imageTypeLimit {
                  params["imageTypeLimit"] = imageTypeLimit
                }
                if let enableImageTypes = options.enableImageTypes?.encode().map({ String(describing: $0) }).joined(separator: ",") {
                  params["enableImageTypes"] = enableImageTypes
                }
                if let excludeItemTypes = options.excludeItemTypes?.joined(separator: ",") {
                  params["excludeItemTypes"] = excludeItemTypes
                }
                if let includeItemTypes = options.includeItemTypes?.joined(separator: ",") {
                  params["includeItemTypes"] = includeItemTypes
                }
                if let enableTotalRecordCount = options.enableTotalRecordCount {
                  params["enableTotalRecordCount"] = enableTotalRecordCount
                }
                if let enableImages = options.enableImages {
                  params["enableImages"] = enableImages
                }
                return params
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = BaseItemDtoQueryResultModel

            /** Items returned. */
            case status200(BaseItemDtoQueryResultModel)

            /** Unauthorized */
            case status401

            /** Forbidden */
            case status403

            public var success: BaseItemDtoQueryResultModel? {
                switch self {
                case .status200(let response): return response
                default: return nil
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                default: return ()
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                case .status401: return 401
                case .status403: return 403
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                case .status401: return false
                case .status403: return false
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(BaseItemDtoQueryResultModel.self, from: data))
                case 401: self = .status401
                case 403: self = .status403
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
