//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension JellyfinAPI.Artists {

    /** Gets all artists from a given item, folder, or the entire library. */
    public enum GetArtists {

        public static let service = APIService<Response>(id: "GetArtists", tag: "Artists", method: "GET", path: "/Artists", hasBody: false, securityRequirements: [SecurityRequirement(type: "CustomAuthentication", scopes: ["DefaultAuthorization"])])

        public final class Request: APIRequest<Response> {

            public struct Options {

                /** Optional filter by minimum community rating. */
                public var minCommunityRating: Double?

                /** Optional. The record index to start at. All items with a lower index will be dropped from the results. */
                public var startIndex: Int?

                /** Optional. The maximum number of records to return. */
                public var limit: Int?

                /** Optional. Search term. */
                public var searchTerm: String?

                /** Specify this to localize the search to a specific item or folder. Omit to use the root. */
                public var parentId: ID?

                /** Optional. Specify additional fields of information to return in the output. */
                public var fields: [ItemFields]?

                /** Optional. If specified, results will be filtered out based on item type. This allows multiple, comma delimited. */
                public var excludeItemTypes: [String]?

                /** Optional. If specified, results will be filtered based on item type. This allows multiple, comma delimited. */
                public var includeItemTypes: [String]?

                /** Optional. Specify additional filters to apply. */
                public var filters: [ItemFilter]?

                /** Optional filter by items that are marked as favorite, or not. */
                public var isFavorite: Bool?

                /** Optional filter by MediaType. Allows multiple, comma delimited. */
                public var mediaTypes: [String]?

                /** Optional. If specified, results will be filtered based on genre. This allows multiple, pipe delimited. */
                public var genres: [String]?

                /** Optional. If specified, results will be filtered based on genre id. This allows multiple, pipe delimited. */
                public var genreIds: [ID]?

                /** Optional. If specified, results will be filtered based on OfficialRating. This allows multiple, pipe delimited. */
                public var officialRatings: [String]?

                /** Optional. If specified, results will be filtered based on tag. This allows multiple, pipe delimited. */
                public var tags: [String]?

                /** Optional. If specified, results will be filtered based on production year. This allows multiple, comma delimited. */
                public var years: [Int]?

                /** Optional, include user data. */
                public var enableUserData: Bool?

                /** Optional, the max number of images to return, per image type. */
                public var imageTypeLimit: Int?

                /** Optional. The image types to include in the output. */
                public var enableImageTypes: [ImageType]?

                /** Optional. If specified, results will be filtered to include only those containing the specified person. */
                public var person: String?

                /** Optional. If specified, results will be filtered to include only those containing the specified person ids. */
                public var personIds: [ID]?

                /** Optional. If specified, along with Person, results will be filtered to include only those containing the specified person and PersonType. Allows multiple, comma-delimited. */
                public var personTypes: [String]?

                /** Optional. If specified, results will be filtered based on studio. This allows multiple, pipe delimited. */
                public var studios: [String]?

                /** Optional. If specified, results will be filtered based on studio id. This allows multiple, pipe delimited. */
                public var studioIds: [ID]?

                /** User id. */
                public var userId: ID?

                /** Optional filter by items whose name is sorted equally or greater than a given input string. */
                public var nameStartsWithOrGreater: String?

                /** Optional filter by items whose name is sorted equally than a given input string. */
                public var nameStartsWith: String?

                /** Optional filter by items whose name is equally or lesser than a given input string. */
                public var nameLessThan: String?

                /** Optional, include image information in output. */
                public var enableImages: Bool?

                /** Total record count. */
                public var enableTotalRecordCount: Bool?

                public init(minCommunityRating: Double? = nil, startIndex: Int? = nil, limit: Int? = nil, searchTerm: String? = nil, parentId: ID? = nil, fields: [ItemFields]? = nil, excludeItemTypes: [String]? = nil, includeItemTypes: [String]? = nil, filters: [ItemFilter]? = nil, isFavorite: Bool? = nil, mediaTypes: [String]? = nil, genres: [String]? = nil, genreIds: [ID]? = nil, officialRatings: [String]? = nil, tags: [String]? = nil, years: [Int]? = nil, enableUserData: Bool? = nil, imageTypeLimit: Int? = nil, enableImageTypes: [ImageType]? = nil, person: String? = nil, personIds: [ID]? = nil, personTypes: [String]? = nil, studios: [String]? = nil, studioIds: [ID]? = nil, userId: ID? = nil, nameStartsWithOrGreater: String? = nil, nameStartsWith: String? = nil, nameLessThan: String? = nil, enableImages: Bool? = nil, enableTotalRecordCount: Bool? = nil) {
                    self.minCommunityRating = minCommunityRating
                    self.startIndex = startIndex
                    self.limit = limit
                    self.searchTerm = searchTerm
                    self.parentId = parentId
                    self.fields = fields
                    self.excludeItemTypes = excludeItemTypes
                    self.includeItemTypes = includeItemTypes
                    self.filters = filters
                    self.isFavorite = isFavorite
                    self.mediaTypes = mediaTypes
                    self.genres = genres
                    self.genreIds = genreIds
                    self.officialRatings = officialRatings
                    self.tags = tags
                    self.years = years
                    self.enableUserData = enableUserData
                    self.imageTypeLimit = imageTypeLimit
                    self.enableImageTypes = enableImageTypes
                    self.person = person
                    self.personIds = personIds
                    self.personTypes = personTypes
                    self.studios = studios
                    self.studioIds = studioIds
                    self.userId = userId
                    self.nameStartsWithOrGreater = nameStartsWithOrGreater
                    self.nameStartsWith = nameStartsWith
                    self.nameLessThan = nameLessThan
                    self.enableImages = enableImages
                    self.enableTotalRecordCount = enableTotalRecordCount
                }
            }

            public var options: Options

            public init(options: Options) {
                self.options = options
                super.init(service: GetArtists.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(minCommunityRating: Double? = nil, startIndex: Int? = nil, limit: Int? = nil, searchTerm: String? = nil, parentId: ID? = nil, fields: [ItemFields]? = nil, excludeItemTypes: [String]? = nil, includeItemTypes: [String]? = nil, filters: [ItemFilter]? = nil, isFavorite: Bool? = nil, mediaTypes: [String]? = nil, genres: [String]? = nil, genreIds: [ID]? = nil, officialRatings: [String]? = nil, tags: [String]? = nil, years: [Int]? = nil, enableUserData: Bool? = nil, imageTypeLimit: Int? = nil, enableImageTypes: [ImageType]? = nil, person: String? = nil, personIds: [ID]? = nil, personTypes: [String]? = nil, studios: [String]? = nil, studioIds: [ID]? = nil, userId: ID? = nil, nameStartsWithOrGreater: String? = nil, nameStartsWith: String? = nil, nameLessThan: String? = nil, enableImages: Bool? = nil, enableTotalRecordCount: Bool? = nil) {
                let options = Options(minCommunityRating: minCommunityRating, startIndex: startIndex, limit: limit, searchTerm: searchTerm, parentId: parentId, fields: fields, excludeItemTypes: excludeItemTypes, includeItemTypes: includeItemTypes, filters: filters, isFavorite: isFavorite, mediaTypes: mediaTypes, genres: genres, genreIds: genreIds, officialRatings: officialRatings, tags: tags, years: years, enableUserData: enableUserData, imageTypeLimit: imageTypeLimit, enableImageTypes: enableImageTypes, person: person, personIds: personIds, personTypes: personTypes, studios: studios, studioIds: studioIds, userId: userId, nameStartsWithOrGreater: nameStartsWithOrGreater, nameStartsWith: nameStartsWith, nameLessThan: nameLessThan, enableImages: enableImages, enableTotalRecordCount: enableTotalRecordCount)
                self.init(options: options)
            }

            public override var queryParameters: [String: Any] {
                var params: [String: Any] = [:]
                if let minCommunityRating = options.minCommunityRating {
                  params["minCommunityRating"] = minCommunityRating
                }
                if let startIndex = options.startIndex {
                  params["startIndex"] = startIndex
                }
                if let limit = options.limit {
                  params["limit"] = limit
                }
                if let searchTerm = options.searchTerm {
                  params["searchTerm"] = searchTerm
                }
                if let parentId = options.parentId?.encode() {
                  params["parentId"] = parentId
                }
                if let fields = options.fields?.encode().map({ String(describing: $0) }).joined(separator: ",") {
                  params["fields"] = fields
                }
                if let excludeItemTypes = options.excludeItemTypes?.joined(separator: ",") {
                  params["excludeItemTypes"] = excludeItemTypes
                }
                if let includeItemTypes = options.includeItemTypes?.joined(separator: ",") {
                  params["includeItemTypes"] = includeItemTypes
                }
                if let filters = options.filters?.encode().map({ String(describing: $0) }).joined(separator: ",") {
                  params["filters"] = filters
                }
                if let isFavorite = options.isFavorite {
                  params["isFavorite"] = isFavorite
                }
                if let mediaTypes = options.mediaTypes?.joined(separator: ",") {
                  params["mediaTypes"] = mediaTypes
                }
                if let genres = options.genres?.joined(separator: ",") {
                  params["genres"] = genres
                }
                if let genreIds = options.genreIds?.encode().map({ String(describing: $0) }).joined(separator: ",") {
                  params["genreIds"] = genreIds
                }
                if let officialRatings = options.officialRatings?.joined(separator: ",") {
                  params["officialRatings"] = officialRatings
                }
                if let tags = options.tags?.joined(separator: ",") {
                  params["tags"] = tags
                }
                if let years = options.years?.map({ String(describing: $0) }).joined(separator: ",") {
                  params["years"] = years
                }
                if let enableUserData = options.enableUserData {
                  params["enableUserData"] = enableUserData
                }
                if let imageTypeLimit = options.imageTypeLimit {
                  params["imageTypeLimit"] = imageTypeLimit
                }
                if let enableImageTypes = options.enableImageTypes?.encode().map({ String(describing: $0) }).joined(separator: ",") {
                  params["enableImageTypes"] = enableImageTypes
                }
                if let person = options.person {
                  params["person"] = person
                }
                if let personIds = options.personIds?.encode().map({ String(describing: $0) }).joined(separator: ",") {
                  params["personIds"] = personIds
                }
                if let personTypes = options.personTypes?.joined(separator: ",") {
                  params["personTypes"] = personTypes
                }
                if let studios = options.studios?.joined(separator: ",") {
                  params["studios"] = studios
                }
                if let studioIds = options.studioIds?.encode().map({ String(describing: $0) }).joined(separator: ",") {
                  params["studioIds"] = studioIds
                }
                if let userId = options.userId?.encode() {
                  params["userId"] = userId
                }
                if let nameStartsWithOrGreater = options.nameStartsWithOrGreater {
                  params["nameStartsWithOrGreater"] = nameStartsWithOrGreater
                }
                if let nameStartsWith = options.nameStartsWith {
                  params["nameStartsWith"] = nameStartsWith
                }
                if let nameLessThan = options.nameLessThan {
                  params["nameLessThan"] = nameLessThan
                }
                if let enableImages = options.enableImages {
                  params["enableImages"] = enableImages
                }
                if let enableTotalRecordCount = options.enableTotalRecordCount {
                  params["enableTotalRecordCount"] = enableTotalRecordCount
                }
                return params
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = BaseItemDtoQueryResultModel

            /** Artists returned. */
            case status200(BaseItemDtoQueryResultModel)

            /** Unauthorized */
            case status401

            /** Forbidden */
            case status403

            public var success: BaseItemDtoQueryResultModel? {
                switch self {
                case .status200(let response): return response
                default: return nil
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                default: return ()
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                case .status401: return 401
                case .status403: return 403
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                case .status401: return false
                case .status403: return false
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(BaseItemDtoQueryResultModel.self, from: data))
                case 401: self = .status401
                case 403: self = .status403
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
