//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension JellyfinAPI.Playlists {

    /** Removes items from a playlist. */
    public enum RemoveFromPlaylist {

        public static let service = APIService<Response>(id: "RemoveFromPlaylist", tag: "Playlists", method: "DELETE", path: "/Playlists/{playlistId}/Items", hasBody: false, securityRequirements: [SecurityRequirement(type: "CustomAuthentication", scopes: ["DefaultAuthorization"])])

        public final class Request: APIRequest<Response> {

            public struct Options {

                /** The playlist id. */
                public var playlistId: String

                /** The item ids, comma delimited. */
                public var entryIds: [String]?

                public init(playlistId: String, entryIds: [String]? = nil) {
                    self.playlistId = playlistId
                    self.entryIds = entryIds
                }
            }

            public var options: Options

            public init(options: Options) {
                self.options = options
                super.init(service: RemoveFromPlaylist.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(playlistId: String, entryIds: [String]? = nil) {
                let options = Options(playlistId: playlistId, entryIds: entryIds)
                self.init(options: options)
            }

            public override var path: String {
                return super.path.replacingOccurrences(of: "{" + "playlistId" + "}", with: "\(self.options.playlistId)")
            }

            public override var queryParameters: [String: Any] {
                var params: [String: Any] = [:]
                if let entryIds = options.entryIds?.joined(separator: ",") {
                  params["entryIds"] = entryIds
                }
                return params
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = Void

            /** Items removed. */
            case status204

            /** Unauthorized */
            case status401

            /** Forbidden */
            case status403

            public var success: Void? {
                switch self {
                case .status204: return ()
                default: return nil
                }
            }

            public var response: Any {
                switch self {
                default: return ()
                }
            }

            public var statusCode: Int {
                switch self {
                case .status204: return 204
                case .status401: return 401
                case .status403: return 403
                }
            }

            public var successful: Bool {
                switch self {
                case .status204: return true
                case .status401: return false
                case .status403: return false
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 204: self = .status204
                case 401: self = .status401
                case 403: self = .status403
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
