//
// ItemLookupAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import AnyCodable
import Foundation
#if canImport(Combine)
import Combine
#endif

open class ItemLookupAPI {
    /**
     Applies search criteria to an item and refreshes metadata.
     
     - parameter itemId: (path) Item id. 
     - parameter applySearchCriteriaRequest: (body) The remote search result. 
     - parameter replaceAllImages: (query) Optional. Whether or not to replace all images. Default: True. (optional, default to true)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: AnyPublisher<Void, Error>
     */
    #if canImport(Combine)
    @available(OSX 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func applySearchCriteria(itemId: String, applySearchCriteriaRequest: ApplySearchCriteriaRequest, replaceAllImages: Bool? = nil, apiResponseQueue: DispatchQueue = JellyfinAPI.apiResponseQueue) -> AnyPublisher<Void, Error> {
        return Future<Void, Error>.init { promise in
            applySearchCriteriaWithRequestBuilder(itemId: itemId, applySearchCriteriaRequest: applySearchCriteriaRequest, replaceAllImages: replaceAllImages).execute(apiResponseQueue) { result -> Void in
                switch result {
                case .success:
                    promise(.success(()))
                case let .failure(error):
                    promise(.failure(error))
                }
            }
        }.eraseToAnyPublisher()
    }
    #endif

    /**
     Applies search criteria to an item and refreshes metadata.
     - POST /Items/RemoteSearch/Apply/{itemId}
     - API Key:
       - type: apiKey Authorization 
       - name: CustomAuthentication
     - parameter itemId: (path) Item id. 
     - parameter applySearchCriteriaRequest: (body) The remote search result. 
     - parameter replaceAllImages: (query) Optional. Whether or not to replace all images. Default: True. (optional, default to true)
     - returns: RequestBuilder<Void> 
     */
    open class func applySearchCriteriaWithRequestBuilder(itemId: String, applySearchCriteriaRequest: ApplySearchCriteriaRequest, replaceAllImages: Bool? = nil) -> RequestBuilder<Void> {
        var urlPath = "/Items/RemoteSearch/Apply/{itemId}"
        let itemIdPreEscape = "\(APIHelper.mapValueToPathItem(itemId))"
        let itemIdPostEscape = itemIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        urlPath = urlPath.replacingOccurrences(of: "{itemId}", with: itemIdPostEscape, options: .literal, range: nil)
        let URLString = JellyfinAPI.basePath + urlPath
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: applySearchCriteriaRequest)

        var urlComponents = URLComponents(string: URLString)
        urlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "replaceAllImages": replaceAllImages?.encodeToJSON(),
        ])

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = JellyfinAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Get book remote search.
     
     - parameter getBookRemoteSearchResultsRequest: (body) Remote search query. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: AnyPublisher<[RemoteSearchResult], Error>
     */
    #if canImport(Combine)
    @available(OSX 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getBookRemoteSearchResults(getBookRemoteSearchResultsRequest: GetBookRemoteSearchResultsRequest, apiResponseQueue: DispatchQueue = JellyfinAPI.apiResponseQueue) -> AnyPublisher<[RemoteSearchResult], Error> {
        return Future<[RemoteSearchResult], Error>.init { promise in
            getBookRemoteSearchResultsWithRequestBuilder(getBookRemoteSearchResultsRequest: getBookRemoteSearchResultsRequest).execute(apiResponseQueue) { result -> Void in
                switch result {
                case let .success(response):
                    promise(.success(response.body!))
                case let .failure(error):
                    promise(.failure(error))
                }
            }
        }.eraseToAnyPublisher()
    }
    #endif

    /**
     Get book remote search.
     - POST /Items/RemoteSearch/Book
     - API Key:
       - type: apiKey Authorization 
       - name: CustomAuthentication
     - parameter getBookRemoteSearchResultsRequest: (body) Remote search query. 
     - returns: RequestBuilder<[RemoteSearchResult]> 
     */
    open class func getBookRemoteSearchResultsWithRequestBuilder(getBookRemoteSearchResultsRequest: GetBookRemoteSearchResultsRequest) -> RequestBuilder<[RemoteSearchResult]> {
        let urlPath = "/Items/RemoteSearch/Book"
        let URLString = JellyfinAPI.basePath + urlPath
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: getBookRemoteSearchResultsRequest)

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[RemoteSearchResult]>.Type = JellyfinAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Get box set remote search.
     
     - parameter getBoxSetRemoteSearchResultsRequest: (body) Remote search query. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: AnyPublisher<[RemoteSearchResult], Error>
     */
    #if canImport(Combine)
    @available(OSX 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getBoxSetRemoteSearchResults(getBoxSetRemoteSearchResultsRequest: GetBoxSetRemoteSearchResultsRequest, apiResponseQueue: DispatchQueue = JellyfinAPI.apiResponseQueue) -> AnyPublisher<[RemoteSearchResult], Error> {
        return Future<[RemoteSearchResult], Error>.init { promise in
            getBoxSetRemoteSearchResultsWithRequestBuilder(getBoxSetRemoteSearchResultsRequest: getBoxSetRemoteSearchResultsRequest).execute(apiResponseQueue) { result -> Void in
                switch result {
                case let .success(response):
                    promise(.success(response.body!))
                case let .failure(error):
                    promise(.failure(error))
                }
            }
        }.eraseToAnyPublisher()
    }
    #endif

    /**
     Get box set remote search.
     - POST /Items/RemoteSearch/BoxSet
     - API Key:
       - type: apiKey Authorization 
       - name: CustomAuthentication
     - parameter getBoxSetRemoteSearchResultsRequest: (body) Remote search query. 
     - returns: RequestBuilder<[RemoteSearchResult]> 
     */
    open class func getBoxSetRemoteSearchResultsWithRequestBuilder(getBoxSetRemoteSearchResultsRequest: GetBoxSetRemoteSearchResultsRequest) -> RequestBuilder<[RemoteSearchResult]> {
        let urlPath = "/Items/RemoteSearch/BoxSet"
        let URLString = JellyfinAPI.basePath + urlPath
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: getBoxSetRemoteSearchResultsRequest)

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[RemoteSearchResult]>.Type = JellyfinAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Get the item's external id info.
     
     - parameter itemId: (path) Item id. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: AnyPublisher<[ExternalIdInfo], Error>
     */
    #if canImport(Combine)
    @available(OSX 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getExternalIdInfos(itemId: String, apiResponseQueue: DispatchQueue = JellyfinAPI.apiResponseQueue) -> AnyPublisher<[ExternalIdInfo], Error> {
        return Future<[ExternalIdInfo], Error>.init { promise in
            getExternalIdInfosWithRequestBuilder(itemId: itemId).execute(apiResponseQueue) { result -> Void in
                switch result {
                case let .success(response):
                    promise(.success(response.body!))
                case let .failure(error):
                    promise(.failure(error))
                }
            }
        }.eraseToAnyPublisher()
    }
    #endif

    /**
     Get the item's external id info.
     - GET /Items/{itemId}/ExternalIdInfos
     - API Key:
       - type: apiKey Authorization 
       - name: CustomAuthentication
     - parameter itemId: (path) Item id. 
     - returns: RequestBuilder<[ExternalIdInfo]> 
     */
    open class func getExternalIdInfosWithRequestBuilder(itemId: String) -> RequestBuilder<[ExternalIdInfo]> {
        var urlPath = "/Items/{itemId}/ExternalIdInfos"
        let itemIdPreEscape = "\(APIHelper.mapValueToPathItem(itemId))"
        let itemIdPostEscape = itemIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        urlPath = urlPath.replacingOccurrences(of: "{itemId}", with: itemIdPostEscape, options: .literal, range: nil)
        let URLString = JellyfinAPI.basePath + urlPath
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[ExternalIdInfo]>.Type = JellyfinAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Get movie remote search.
     
     - parameter getMovieRemoteSearchResultsRequest: (body) Remote search query. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: AnyPublisher<[RemoteSearchResult], Error>
     */
    #if canImport(Combine)
    @available(OSX 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getMovieRemoteSearchResults(getMovieRemoteSearchResultsRequest: GetMovieRemoteSearchResultsRequest, apiResponseQueue: DispatchQueue = JellyfinAPI.apiResponseQueue) -> AnyPublisher<[RemoteSearchResult], Error> {
        return Future<[RemoteSearchResult], Error>.init { promise in
            getMovieRemoteSearchResultsWithRequestBuilder(getMovieRemoteSearchResultsRequest: getMovieRemoteSearchResultsRequest).execute(apiResponseQueue) { result -> Void in
                switch result {
                case let .success(response):
                    promise(.success(response.body!))
                case let .failure(error):
                    promise(.failure(error))
                }
            }
        }.eraseToAnyPublisher()
    }
    #endif

    /**
     Get movie remote search.
     - POST /Items/RemoteSearch/Movie
     - API Key:
       - type: apiKey Authorization 
       - name: CustomAuthentication
     - parameter getMovieRemoteSearchResultsRequest: (body) Remote search query. 
     - returns: RequestBuilder<[RemoteSearchResult]> 
     */
    open class func getMovieRemoteSearchResultsWithRequestBuilder(getMovieRemoteSearchResultsRequest: GetMovieRemoteSearchResultsRequest) -> RequestBuilder<[RemoteSearchResult]> {
        let urlPath = "/Items/RemoteSearch/Movie"
        let URLString = JellyfinAPI.basePath + urlPath
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: getMovieRemoteSearchResultsRequest)

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[RemoteSearchResult]>.Type = JellyfinAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Get music album remote search.
     
     - parameter getMusicAlbumRemoteSearchResultsRequest: (body) Remote search query. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: AnyPublisher<[RemoteSearchResult], Error>
     */
    #if canImport(Combine)
    @available(OSX 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getMusicAlbumRemoteSearchResults(getMusicAlbumRemoteSearchResultsRequest: GetMusicAlbumRemoteSearchResultsRequest, apiResponseQueue: DispatchQueue = JellyfinAPI.apiResponseQueue) -> AnyPublisher<[RemoteSearchResult], Error> {
        return Future<[RemoteSearchResult], Error>.init { promise in
            getMusicAlbumRemoteSearchResultsWithRequestBuilder(getMusicAlbumRemoteSearchResultsRequest: getMusicAlbumRemoteSearchResultsRequest).execute(apiResponseQueue) { result -> Void in
                switch result {
                case let .success(response):
                    promise(.success(response.body!))
                case let .failure(error):
                    promise(.failure(error))
                }
            }
        }.eraseToAnyPublisher()
    }
    #endif

    /**
     Get music album remote search.
     - POST /Items/RemoteSearch/MusicAlbum
     - API Key:
       - type: apiKey Authorization 
       - name: CustomAuthentication
     - parameter getMusicAlbumRemoteSearchResultsRequest: (body) Remote search query. 
     - returns: RequestBuilder<[RemoteSearchResult]> 
     */
    open class func getMusicAlbumRemoteSearchResultsWithRequestBuilder(getMusicAlbumRemoteSearchResultsRequest: GetMusicAlbumRemoteSearchResultsRequest) -> RequestBuilder<[RemoteSearchResult]> {
        let urlPath = "/Items/RemoteSearch/MusicAlbum"
        let URLString = JellyfinAPI.basePath + urlPath
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: getMusicAlbumRemoteSearchResultsRequest)

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[RemoteSearchResult]>.Type = JellyfinAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Get music artist remote search.
     
     - parameter getMusicArtistRemoteSearchResultsRequest: (body) Remote search query. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: AnyPublisher<[RemoteSearchResult], Error>
     */
    #if canImport(Combine)
    @available(OSX 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getMusicArtistRemoteSearchResults(getMusicArtistRemoteSearchResultsRequest: GetMusicArtistRemoteSearchResultsRequest, apiResponseQueue: DispatchQueue = JellyfinAPI.apiResponseQueue) -> AnyPublisher<[RemoteSearchResult], Error> {
        return Future<[RemoteSearchResult], Error>.init { promise in
            getMusicArtistRemoteSearchResultsWithRequestBuilder(getMusicArtistRemoteSearchResultsRequest: getMusicArtistRemoteSearchResultsRequest).execute(apiResponseQueue) { result -> Void in
                switch result {
                case let .success(response):
                    promise(.success(response.body!))
                case let .failure(error):
                    promise(.failure(error))
                }
            }
        }.eraseToAnyPublisher()
    }
    #endif

    /**
     Get music artist remote search.
     - POST /Items/RemoteSearch/MusicArtist
     - API Key:
       - type: apiKey Authorization 
       - name: CustomAuthentication
     - parameter getMusicArtistRemoteSearchResultsRequest: (body) Remote search query. 
     - returns: RequestBuilder<[RemoteSearchResult]> 
     */
    open class func getMusicArtistRemoteSearchResultsWithRequestBuilder(getMusicArtistRemoteSearchResultsRequest: GetMusicArtistRemoteSearchResultsRequest) -> RequestBuilder<[RemoteSearchResult]> {
        let urlPath = "/Items/RemoteSearch/MusicArtist"
        let URLString = JellyfinAPI.basePath + urlPath
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: getMusicArtistRemoteSearchResultsRequest)

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[RemoteSearchResult]>.Type = JellyfinAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Get music video remote search.
     
     - parameter getMusicVideoRemoteSearchResultsRequest: (body) Remote search query. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: AnyPublisher<[RemoteSearchResult], Error>
     */
    #if canImport(Combine)
    @available(OSX 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getMusicVideoRemoteSearchResults(getMusicVideoRemoteSearchResultsRequest: GetMusicVideoRemoteSearchResultsRequest, apiResponseQueue: DispatchQueue = JellyfinAPI.apiResponseQueue) -> AnyPublisher<[RemoteSearchResult], Error> {
        return Future<[RemoteSearchResult], Error>.init { promise in
            getMusicVideoRemoteSearchResultsWithRequestBuilder(getMusicVideoRemoteSearchResultsRequest: getMusicVideoRemoteSearchResultsRequest).execute(apiResponseQueue) { result -> Void in
                switch result {
                case let .success(response):
                    promise(.success(response.body!))
                case let .failure(error):
                    promise(.failure(error))
                }
            }
        }.eraseToAnyPublisher()
    }
    #endif

    /**
     Get music video remote search.
     - POST /Items/RemoteSearch/MusicVideo
     - API Key:
       - type: apiKey Authorization 
       - name: CustomAuthentication
     - parameter getMusicVideoRemoteSearchResultsRequest: (body) Remote search query. 
     - returns: RequestBuilder<[RemoteSearchResult]> 
     */
    open class func getMusicVideoRemoteSearchResultsWithRequestBuilder(getMusicVideoRemoteSearchResultsRequest: GetMusicVideoRemoteSearchResultsRequest) -> RequestBuilder<[RemoteSearchResult]> {
        let urlPath = "/Items/RemoteSearch/MusicVideo"
        let URLString = JellyfinAPI.basePath + urlPath
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: getMusicVideoRemoteSearchResultsRequest)

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[RemoteSearchResult]>.Type = JellyfinAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Get person remote search.
     
     - parameter getPersonRemoteSearchResultsRequest: (body) Remote search query. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: AnyPublisher<[RemoteSearchResult], Error>
     */
    #if canImport(Combine)
    @available(OSX 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getPersonRemoteSearchResults(getPersonRemoteSearchResultsRequest: GetPersonRemoteSearchResultsRequest, apiResponseQueue: DispatchQueue = JellyfinAPI.apiResponseQueue) -> AnyPublisher<[RemoteSearchResult], Error> {
        return Future<[RemoteSearchResult], Error>.init { promise in
            getPersonRemoteSearchResultsWithRequestBuilder(getPersonRemoteSearchResultsRequest: getPersonRemoteSearchResultsRequest).execute(apiResponseQueue) { result -> Void in
                switch result {
                case let .success(response):
                    promise(.success(response.body!))
                case let .failure(error):
                    promise(.failure(error))
                }
            }
        }.eraseToAnyPublisher()
    }
    #endif

    /**
     Get person remote search.
     - POST /Items/RemoteSearch/Person
     - API Key:
       - type: apiKey Authorization 
       - name: CustomAuthentication
     - parameter getPersonRemoteSearchResultsRequest: (body) Remote search query. 
     - returns: RequestBuilder<[RemoteSearchResult]> 
     */
    open class func getPersonRemoteSearchResultsWithRequestBuilder(getPersonRemoteSearchResultsRequest: GetPersonRemoteSearchResultsRequest) -> RequestBuilder<[RemoteSearchResult]> {
        let urlPath = "/Items/RemoteSearch/Person"
        let URLString = JellyfinAPI.basePath + urlPath
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: getPersonRemoteSearchResultsRequest)

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[RemoteSearchResult]>.Type = JellyfinAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Get series remote search.
     
     - parameter getSeriesRemoteSearchResultsRequest: (body) Remote search query. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: AnyPublisher<[RemoteSearchResult], Error>
     */
    #if canImport(Combine)
    @available(OSX 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getSeriesRemoteSearchResults(getSeriesRemoteSearchResultsRequest: GetSeriesRemoteSearchResultsRequest, apiResponseQueue: DispatchQueue = JellyfinAPI.apiResponseQueue) -> AnyPublisher<[RemoteSearchResult], Error> {
        return Future<[RemoteSearchResult], Error>.init { promise in
            getSeriesRemoteSearchResultsWithRequestBuilder(getSeriesRemoteSearchResultsRequest: getSeriesRemoteSearchResultsRequest).execute(apiResponseQueue) { result -> Void in
                switch result {
                case let .success(response):
                    promise(.success(response.body!))
                case let .failure(error):
                    promise(.failure(error))
                }
            }
        }.eraseToAnyPublisher()
    }
    #endif

    /**
     Get series remote search.
     - POST /Items/RemoteSearch/Series
     - API Key:
       - type: apiKey Authorization 
       - name: CustomAuthentication
     - parameter getSeriesRemoteSearchResultsRequest: (body) Remote search query. 
     - returns: RequestBuilder<[RemoteSearchResult]> 
     */
    open class func getSeriesRemoteSearchResultsWithRequestBuilder(getSeriesRemoteSearchResultsRequest: GetSeriesRemoteSearchResultsRequest) -> RequestBuilder<[RemoteSearchResult]> {
        let urlPath = "/Items/RemoteSearch/Series"
        let URLString = JellyfinAPI.basePath + urlPath
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: getSeriesRemoteSearchResultsRequest)

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[RemoteSearchResult]>.Type = JellyfinAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Get trailer remote search.
     
     - parameter getTrailerRemoteSearchResultsRequest: (body) Remote search query. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: AnyPublisher<[RemoteSearchResult], Error>
     */
    #if canImport(Combine)
    @available(OSX 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getTrailerRemoteSearchResults(getTrailerRemoteSearchResultsRequest: GetTrailerRemoteSearchResultsRequest, apiResponseQueue: DispatchQueue = JellyfinAPI.apiResponseQueue) -> AnyPublisher<[RemoteSearchResult], Error> {
        return Future<[RemoteSearchResult], Error>.init { promise in
            getTrailerRemoteSearchResultsWithRequestBuilder(getTrailerRemoteSearchResultsRequest: getTrailerRemoteSearchResultsRequest).execute(apiResponseQueue) { result -> Void in
                switch result {
                case let .success(response):
                    promise(.success(response.body!))
                case let .failure(error):
                    promise(.failure(error))
                }
            }
        }.eraseToAnyPublisher()
    }
    #endif

    /**
     Get trailer remote search.
     - POST /Items/RemoteSearch/Trailer
     - API Key:
       - type: apiKey Authorization 
       - name: CustomAuthentication
     - parameter getTrailerRemoteSearchResultsRequest: (body) Remote search query. 
     - returns: RequestBuilder<[RemoteSearchResult]> 
     */
    open class func getTrailerRemoteSearchResultsWithRequestBuilder(getTrailerRemoteSearchResultsRequest: GetTrailerRemoteSearchResultsRequest) -> RequestBuilder<[RemoteSearchResult]> {
        let urlPath = "/Items/RemoteSearch/Trailer"
        let URLString = JellyfinAPI.basePath + urlPath
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: getTrailerRemoteSearchResultsRequest)

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[RemoteSearchResult]>.Type = JellyfinAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

}
