name: Generate stable API

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        ref: 'main'

    - name: Setup Mint	    
      uses: irgaly/setup-mint@v1

    - name: Download api.json
      run: curl https://api.jellyfin.org/openapi/jellyfin-openapi-stable.json -o jellyfin-openapi-stable.json

    - name: Generate	    
      run: |
        mint run CreateAPI create-api generate
        jellyfin-openapi-stable.json 
        --package JellyfinAPI 
        --output .

    # "echo" in commit returns true so the build succeeds, even if no changed files
    - name: Commit new changes to the repo
      run: |
        git config user.name jellyfin-bot
        git config user.email team@jellyfin.org
        git pull
        git add .
        git commit -m "Update stable JellyfinAPI client" || echo
        git push
