//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension JellyfinAPI.Playstate {

    /** Reports that a user has stopped playing an item. */
    public enum OnPlaybackStopped {

        public static let service = APIService<Response>(id: "OnPlaybackStopped", tag: "Playstate", method: "DELETE", path: "/Users/{userId}/PlayingItems/{itemId}", hasBody: false, securityRequirements: [SecurityRequirement(type: "CustomAuthentication", scopes: ["DefaultAuthorization"])])

        public final class Request: APIRequest<Response> {

            public struct Options {

                /** User id. */
                public var userId: ID

                /** Item id. */
                public var itemId: ID

                /** The id of the MediaSource. */
                public var mediaSourceId: String?

                /** The next media type that will play. */
                public var nextMediaType: String?

                /** Optional. The position, in ticks, where playback stopped. 1 tick = 10000 ms. */
                public var positionTicks: Int?

                /** The live stream id. */
                public var liveStreamId: String?

                /** The play session id. */
                public var playSessionId: String?

                public init(userId: ID, itemId: ID, mediaSourceId: String? = nil, nextMediaType: String? = nil, positionTicks: Int? = nil, liveStreamId: String? = nil, playSessionId: String? = nil) {
                    self.userId = userId
                    self.itemId = itemId
                    self.mediaSourceId = mediaSourceId
                    self.nextMediaType = nextMediaType
                    self.positionTicks = positionTicks
                    self.liveStreamId = liveStreamId
                    self.playSessionId = playSessionId
                }
            }

            public var options: Options

            public init(options: Options) {
                self.options = options
                super.init(service: OnPlaybackStopped.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(userId: ID, itemId: ID, mediaSourceId: String? = nil, nextMediaType: String? = nil, positionTicks: Int? = nil, liveStreamId: String? = nil, playSessionId: String? = nil) {
                let options = Options(userId: userId, itemId: itemId, mediaSourceId: mediaSourceId, nextMediaType: nextMediaType, positionTicks: positionTicks, liveStreamId: liveStreamId, playSessionId: playSessionId)
                self.init(options: options)
            }

            public override var path: String {
                return super.path.replacingOccurrences(of: "{" + "userId" + "}", with: "\(self.options.userId.encode())").replacingOccurrences(of: "{" + "itemId" + "}", with: "\(self.options.itemId.encode())")
            }

            public override var queryParameters: [String: Any] {
                var params: [String: Any] = [:]
                if let mediaSourceId = options.mediaSourceId {
                  params["mediaSourceId"] = mediaSourceId
                }
                if let nextMediaType = options.nextMediaType {
                  params["nextMediaType"] = nextMediaType
                }
                if let positionTicks = options.positionTicks {
                  params["positionTicks"] = positionTicks
                }
                if let liveStreamId = options.liveStreamId {
                  params["liveStreamId"] = liveStreamId
                }
                if let playSessionId = options.playSessionId {
                  params["playSessionId"] = playSessionId
                }
                return params
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = Void

            /** Playback stop recorded. */
            case status204

            /** Unauthorized */
            case status401

            /** Forbidden */
            case status403

            public var success: Void? {
                switch self {
                case .status204: return ()
                default: return nil
                }
            }

            public var response: Any {
                switch self {
                default: return ()
                }
            }

            public var statusCode: Int {
                switch self {
                case .status204: return 204
                case .status401: return 401
                case .status403: return 403
                }
            }

            public var successful: Bool {
                switch self {
                case .status204: return true
                case .status401: return false
                case .status403: return false
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 204: self = .status204
                case 401: self = .status401
                case 403: self = .status403
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
